### ISSUE TITLE
androidSessions should be an int

### ISSUE THREAD

**Issue by kolibrigames-ajimine-vahid** [Appboy/appboy-unity-sdk#70] opened 2020-09-25 07:15 UTC
https://github.com/Appboy/appboy-unity-sdk/blob/40571203194e8fb3fa088d11246c7c5343b6543c/Assets/Plugins/Appboy/Editor/AppboyConfig.cs#L46

This should be an `int`.

https://github.com/Appboy/appboy-unity-sdk/blob/cbea9db679123459a96a5e85310aac46f563ed67/Assets/Plugins/Appboy/Editor/PreBuild.cs#L122

You literally have a method that converts a string to an it which is not necessary and only add additional complexity since you already have this:

https://github.com/Appboy/appboy-unity-sdk/blob/cbea9db679123459a96a5e85310aac46f563ed67/Assets/Plugins/Appboy/Editor/PreBuild.cs#L130

Also, the Editor `ScriptableObjects` can take `int` values.

**Comment by radixdev** [comment] 2020-10-01 16:07
Hi @kolibrigames-ajimine-vahid ,

Is this a duplicate of https://github.com/Appboy/appboy-unity-sdk/issues/69 ?

**Comment by kolibrigames-ajimine-vahid** [comment] 2020-10-01 16:11
Yes. I created this as the other issue was closed

**Comment by radixdev** [comment] 2020-10-01 16:38
closed as duplicated and reopened the original issue

**Closed** 2020-10-01 16:38 UTC
